version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: https://github.com/DenisseVenegas/repo-test-backend.git
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/testdb
      API_KEY: ${API_KEY}
    ports:
      - "8000:8000"

volumes:
  postgres_data:
